# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        hwi:
            id: hwi_oauth.user.provider

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: true
            logout:
                path: /logout
                target: /
            oauth:
                resource_owners:
                    google: "/login/check-google"
                login_path:        /login
                failure_path:      /login
                oauth_user_provider:
                    service: hwi_oauth.user.provider

    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/book, roles: ROLE_OAUTH_USER }
